export const MULTI_VALUE_MOVIE_FIELDS = {
	'written by': 'writers',
	'screenplay by': 'writers',
	'story by': 'writers',
	starring: 'cast',
	cast: 'cast',
	'produced by': 'producers',
	producer: 'producers',
	producers: 'producers',
	'music by': 'composers',
	'composed by': 'composers',
	composer: 'composers',
	'production companies': 'productionCompanies',
	'production company': 'productionCompanies',
	studio: 'productionCompanies',
	studios: 'productionCompanies',
	'distributed by': 'distributedBy',
	distributor: 'distributedBy',
	country: 'country',
	countries: 'country',
	language: 'language',
	languages: 'language',
	genre: 'genres',
	genres: 'genres',
	'filming locations': 'filmingLocations',
	'filmed in': 'filmingLocations',
	format: 'formats',
	formats: 'formats',
};

export const STRING_MOVIE_FIELDS = {
	'directed by': 'director',
	director: 'director',
	'release date': 'releaseDate',
	'release dates': 'releaseDate',
	'running time': 'runtime',
	runtime: 'runtime',
	budget: 'budget',
	'box office': 'boxOffice',
	gross: 'boxOffice',
};

export const MAIN_MOVIE_FIELDS = [
	'writers',
	'cast',
	'producers',
	'composers',
	'productionCompanies',
	'distributedBy',
	'country',
	'language',
	'genres',
	'themes',
	'formats',
	'filmingLocations',
	'categories',
];
